name = "cf-tv-service"
main = "worker-entry.js"
compatibility_date = "2023-05-18"
account_id = "83bc7552e54dd94303f04ef8d7429066"

# 本地开发
[[kv_namespaces]]
binding = "KV"
id = "local-kv-placeholder"
preview_id = "local-kv-placeholder"

[[d1_databases]]
binding = "DB"
database_name = "tv-service-db"
database_id = "local-d1-placeholder"

[ai]
binding = "AI"

[vars]
TIMEZONE = "Asia/Shanghai"
APP_URL = "https://iptv-search.com"

[triggers]
crons = ["0 3 * * *"]

# 生产环境
[env.production]

[[env.production.kv_namespaces]]
binding = "KV"
id = "d5e943d023d0474382b04b3c15c47ffb"

[[env.production.d1_databases]]
binding = "DB"
database_name = "tv-service-db"
database_id = "9c7c22f1-fa0e-48da-8874-19731483c550"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "static-assets"

[env.production.ai]
binding = "AI"

[env.production.vars]
TIMEZONE = "Asia/Shanghai"
APP_URL = "https://iptv-search.com"
