#!/usr/bin/env python3
"""Generate redesigned generateSEOHomepage - v3"""
with open(r'C:\Users\60270\Desktop\cfworker2\home-page.js', 'r', encoding='utf-8') as f:
    home_content = f.read()
with open(r'C:\Users\60270\Desktop\cfworker2\handlers\seo-handler.js', 'r', encoding='utf-8') as f:
    seo_content = f.read()

style_start = home_content.index('<style>') + 7
style_end = home_content.index('</style>')
css = home_content[style_start:style_end]

def js_escape(s):
    return s.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')

css_escaped = js_escape(css)

# Build function lines - careful with quotes
def L(s): return s

lines = [
L('// ====================================================================='),
L('// 方案D: 静态首页 - 完整复刻 home-page.js 布局'),
L('// Play 按钮: admin 可禁用 IP 直连（enable_ip_play），禁用时跳频道页'),
L('// ====================================================================='),
L(''),
L("import { getSystemConfig } from '../database.js';"),
L(''),
L('export async function generateSEOHomepage(request, env) {'),
L('  const url = new URL(request.url);'),
L('  const origin = `${url.protocol}//${url.host}`;'),
L(''),
L('  const channelsResult = await getAllChannels(env);'),
L('  const groupsResult = await getAllGroups(env);'),
L('  const channels = channelsResult.channels || [];'),
L('  const groups = groupsResult.groups || [];'),
L(''),
L('  const systemConfig = await getSystemConfig(env);'),
L('  const enableIpPlay = systemConfig.enable_ip_play !== false;'),
L(''),
L('  const perPage = 100;'),
L('  const totalChannels = channels.length;'),
L('  const totalPages = Math.max(1, Math.ceil(totalChannels / perPage));'),
L(''),
L('  const pageTitle = `IPTV Search \u2014 Free IPTV Channel Directory & Search Engine`;'),
L('  const metaDescription = `Search over ${channels.length} free IPTV channels from around the world. Sports, news, movies, entertainment. No registration required. Updated daily.`;'),
L(''),
L('  const jsonLd = {'),
L("    '@context': 'https://schema.org',"),
L("    '@type': 'WebSite',"),
L("    'name': 'IPTV Search',"),
L('    \'description\': `Free IPTV channel directory with ${channels.length}+ live TV channels.`,'),
L('    \'url\': origin,'),
L('    \'potentialAction\': {'),
L("      '@type': 'SearchAction',"),
L('      \'target\': { \'@type\': \'EntryPoint\', \'urlTemplate\': `${origin}/search?q={search_term_string}` }, '),
L("      'query-input': 'required name=q'"),
L('    }'),
L('  };'),
L(''),
L('  // ===== 原版完整 CSS（32KB） ====='),
L('  const ORIGINAL_CSS = `' + css_escaped + '`;'),
L(''),
L('  // ===== Header HTML（静态化，无 JS 事件） ====='),
L('  const STATIC_HEADER = `'),
L('    <header class="header">'),
L('      <div class="header-left">'),
L('        <a href="${origin}/" class="logo-link">'),
L('          <div class="logo">'),
L('            <img src="${origin}/logo.svg" alt="IPTV Search Logo" />'),
L('          </div>'),
L('        </a>'),
L('        <div class="online-counter">'),
L('          <span class="online-dot"></span>'),
L('          <span class="online-count">${totalChannels.toLocaleString()}</span>'),
L('          <span>channels</span>'),
L('        </div>'),
L('      </div>'),
L('      <div class="header-right">'),
L('        <div class="search-box">'),
L('          <form action="${origin}/search" method="get">'),
L('            <input type="text" name="q" class="search-input" placeholder="Search channels..." aria-label="Search channels">'),
L('          </form>'),
L('        </div>'),
L('        <div class="quick-entries">'),
L('          <a class="quick-entry" href="${origin}/tutorial" title="How to Watch">'),
L('            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>'),
L('            <span class="quick-entry-tip">How to Watch</span>'),
L('          </a>'),
L('          <a class="quick-entry" href="${origin}/freesub" title="Plans">'),
L('            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>'),
L('            <span class="quick-entry-tip">Plans</span>'),
L('          </a>'),
L('          <a class="quick-entry" href="${origin}/privacy-policy" title="Privacy">'),
L('            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>'),
L('            <span class="quick-entry-tip">Privacy</span>'),
L('          </a>'),
L('        </div>'),
L('        <a class="auth-btn" href="${origin}/login">Login</a>'),
L('        <div id="translate">'),
L('          <select onchange="if(this.value)location.href=this.value">'),
L('            <option value="${origin}/?lang=en">English</option>'),
L('            <option value="${origin}/?lang=zh-CN">\u4e2d\u6587</option>'),
L('          </select>'),
L('        </div>'),
L('      </div>'),
L('    </header>`;'),
L(''),
L('  // ===== Sidebar 分组导航 ====='),
L('  const sidebarItems = groups.slice(0, 100).map(g => {'),
L('    const safeGroup = slugify(g);'),
L('    const count = channels.filter(ch => ch.group_title === g).length;'),
L('    return `<div class="group-item"><a href="${origin}/category/${safeGroup}" style="color:rgba(255,255,255,0.7);text-decoration:none;display:block">${escapeHtml(g)} <span style="opacity:0.5;font-size:0.8em">(${count})</span></a></div>`;'),
L('  }).join("\'");'),
L(''),
L('  const STATIC_SIDEBAR = `'),
L('    <aside class="sidebar" id="sidebar">'),
L('      <div class="group-item active"><a href="${origin}/" style="color:#fff;text-decoration:none;display:block">All Channels</a></div>'),
L('      ${sidebarItems}'),
L('    </aside>`;'),
L(''),
L('  // ===== 频道网格卡片（原版海报样式） ====='),
L('  const channelCardsHtml = channels.slice(0, perPage).map(ch => {'),
L('    const logo = ch.logo'),
L('      ? `<img src="${escapeAttr(ch.logo)}" alt="${escapeHtml(ch.channel_name)}" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'flex\'"><div class="channel-icon" style="display:none;">\uD83D\uDCFA</div>`'),
L('      : `<div class="channel-icon">\uD83D\uDCFA</div>`;'),
L('    return `<div class="channel-card">'),
L('      <div class="channel-poster">'),
L('        <a href="${origin}/channel/${escapeAttr(ch.channel_hash)}" style="display:block;width:100%;height:100%;text-decoration:none">'),
L('          ${logo}'),
L('        </a>'),
L('        <a href="${origin}/channel/${escapeAttr(ch.channel_hash)}" class="play-overlay" style="display:flex;align-items:center;justify-content:center;position:absolute;top:0;left:0;right:0;bottom:0;background:rgba(229,9,20,0.8);opacity:0;transition:opacity .3s;text-decoration:none">'),
L('          <div style="width:60px;height:60px;border:3px solid #fff;border-radius:50%;display:flex;align-items:center;justify-content:center">'),
L('            <svg width="24" height="24" viewBox="0 0 24 24" fill="white"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>'),
L('          </div>'),
L('        </a>'),
L('      </div>'),
L('      <div class="channel-info">'),
L('        <div class="channel-name">'),
L('          <a href="${origin}/channel/${escapeAttr(ch.channel_hash)}" style="color:#fff;text-decoration:none" title="${escapeHtml(ch.channel_name)}">${escapeHtml(ch.channel_name)}</a>'),
L('        </div>'),
L('        <div class="channel-group">${escapeHtml(ch.group_title || "")}</div>'),
L('      </div>'),
L('    </div>`;'),
L('  }).join("\'");'),
L(''),
L('  // ===== 分页导航 ====='),
L('  let paginationHtml = "";'),
L('  if (totalPages > 1) {'),
L('    paginationHtml = `<div class="pagination" style="display:flex;gap:8px;flex-wrap:wrap;margin:20px 0;justify-content:center">`;'),
L('    paginationHtml += `<a href="${origin}/page/2" style="padding:8px 16px;background:#1a1a1a;border:1px solid rgba(255,255,255,0.1);border-radius:6px;color:#fff;text-decoration:none;font-size:14px">Next \u2192</a>`;'),
L('    paginationHtml += `</div>`;'),
L('  }'),
L(''),
L('  // ===== Play 覆盖层 JS（admin enable_ip_play 禁用时跳频道页） ====='),
L('  const playOverlayJS = `'),
L('    <script>'),
L('    window.enableIpPlay = ' + ('true' if True else 'false') + ';'),
L('    document.querySelectorAll(".play-overlay").forEach(function(overlay) {'),
L('      overlay.addEventListener("click", function(e) {'),
L('        e.preventDefault();'),
L('        var href = overlay.getAttribute("href");'),
L('        var hash = (href.split("/channel/")[1] || "");'),
L('        var apiUrl = "${origin}/api/play/link?hash=" + hash;'),
L('        var btn = overlay.querySelector("div") || overlay;'),
L('        btn.style.opacity = "0.5";'),
L('        fetch(apiUrl)'),
L('          .then(function(r) { return r.json(); })'),
L('          .then(function(data) {'),
L('            if (data.success && data.play_link) {'),
L('              window.location.href = data.play_link;'),
L('            } else {'),
L('              window.location.href = href;'),
L('            }'),
L('          })'),
L('          .catch(function() {'),
L('            window.location.href = href;'),
L('          });'),
L('      });'),
L('    });'),
L('    </script>`;'),
L(''),
L('  const sectionLabel = `All Channels <span style="color:rgba(255,255,255,0.5);font-weight:400;font-size:14px;margin-left:12px">${totalChannels.toLocaleString()} channels</span>`;'),
L(''),
L('  const html = `<!DOCTYPE html>'),
L('<html lang="en">'),
L('<head>'),
L('  <meta charset="UTF-8">'),
L('  <meta name="viewport" content="width=device-width, initial-scale=1.0">'),
L('  <title>${escapeHtml(pageTitle)}</title>'),
L('  <meta name="description" content="${escapeAttr(metaDescription)}">'),
L('  <meta name="robots" content="index, follow, max-image-preview:large">'),
L('  <link rel="canonical" href="${origin}/">'),
L('  <link rel="alternate" hreflang="en" href="${origin}/">'),
L('  <link rel="alternate" hreflang="zh-CN" href="${origin}/?lang=zh-CN">'),
L('  <link rel="alternate" hreflang="x-default" href="${origin}/">'),
L('  <link rel="icon" type="image/svg+xml" href="${origin}/favicon.svg">'),
L('  <link rel="apple-touch-icon" href="${origin}/apple-touch-icon.png" sizes="180x180">'),
L('  <meta property="og:type" content="website">'),
L('  <meta property="og:url" content="${origin}/">'),
L('  <meta property="og:title" content="${escapeAttr(pageTitle)}">'),
L('  <meta property="og:description" content="${escapeAttr(metaDescription)}">'),
L('  <meta property="og:image" content="${origin}/og-homepage.png">'),
L('  <meta property="og:image:width" content="1200">'),
L('  <meta property="og:image:height" content="630">'),
L('  <meta property="og:site_name" content="IPTV Search">'),
L('  <meta name="twitter:card" content="summary_large_image">'),
L('  <meta name="twitter:title" content="${escapeAttr(pageTitle)}">'),
L('  <meta name="twitter:description" content="${escapeAttr(metaDescription)}">'),
L('  <meta name="twitter:image" content="${origin}/og-homepage.png">'),
L('  <script type="application/ld+json">${JSON.stringify(jsonLd)}</script>'),
L('  <script type="application/ld+json>'),
L('  {'),
L('    "@context": "https://schema.org",'),
L('    "@type": "FAQPage",'),
L('    "mainEntity": ['),
L('      {"@type": "Question", "name": "What is IPTV Search?", "acceptedAnswer": {"@type": "Answer", "text": "IPTV Search indexes public IPTV channel playlists. Find sports, news, movies, entertainment, and international TV channels \u2014 no subscription required."}},'),
L('      {"@type": "Question", "name": "How do I use IPTV channels?", "acceptedAnswer": {"@type": "Answer", "text": "Find the channel you want, copy its M3U URL, and add it to any IPTV player app such as VLC, IPTV Smarters, or your smart TV."}},'),
L('      {"@type": "Question", "name": "How many channels are available?", "acceptedAnswer": {"@type": "Answer", "text": "We index ${channels.length.toLocaleString()}+ live TV channels across ${groups.length} categories."}},'),
L('      {"@type": "Question", "name": "Is registration required?", "acceptedAnswer": {"@type": "Answer", "text": "No. Browse channels, get the M3U URL, and use it with any compatible player \u2014 completely free."}}'),
L('    ]'),
L('  }'),
L('  </script>'),
L('  <style>${ORIGINAL_CSS}</style>'),
L('</head>'),
L('<body>'),
L('  ${STATIC_HEADER}'),
L(''),
L('  <div class="main">'),
L('    ${STATIC_SIDEBAR}'),
L(''),
L('    <div class="content">'),
L('      <div class="section-title" style="font-size:18px;font-weight:600;margin-bottom:20px;color:#fff">'),
L('        ${sectionLabel}'),
L('      </div>'),
L('      <div class="channels-grid">'),
L('        ${channelCardsHtml}'),
L('      </div>'),
L('      ${paginationHtml}'),
L('    </div>'),
L('  </div>'),
L(''),
L('  ${PAGE_FOOTER}'),
L('  ${playOverlayJS}'),
L('</body>'),
L('</html>`;'),
L(''),
L('  return new Response(html, {'),
L('    status: 200,'),
L('    headers: {'),
L('      \'Content-Type\': \'text/html; charset=utf-8\','),
L('      \'Cache-Control\': \'public, max-age=300\','),
L('      \'X-Seo-Version\': \'3.0\''),
L('    }'),
L('  });'),
L('}'),
]

new_func = '\n'.join(lines)

func_start = seo_content.index('export async function generateSEOHomepage')
func_end = seo_content.index('export async function generateChannelPage')
print(f"Replacing {func_start}:{func_end} ({func_end - func_start} chars)")

new_seo = seo_content[:func_start] + new_func + '\n\n' + seo_content[func_end:]

with open(r'C:\Users\60270\Desktop\cfworker2\handlers\seo-handler.js', 'w', encoding='utf-8') as f:
    f.write(new_seo)

print(f"Written {len(new_seo)} chars. Done!")
